CALL sp_InsertRecipe("Brownies", 1, @recipeID);
CALL sp_InsertRecipeIngredient(@recipeID, 1, 1, "Mel", "300 gram");
CALL sp_InsertRecipeIngredient(@recipeID, 2, 1, "Sukker", "200 gram");
CALL sp_InsertRecipeIngredient(@recipeID, 3, 1, "Kanel", "10 gram");
CALL sp_InsertRecipeIngredient(@recipeID, 4, 1, "Lime Jucie", "2 SS");
CALL sp_InsertRecipeStep(@recipeID,5,1, "Steg 1");
CALL sp_InsertRecipeStep(@recipeID,6,1, "Steg 2");
CALL sp_InsertRecipeStep(@recipeID,7,1, "Steg 3");
CALL sp_InsertRecipeText(@recipeID,8,1, "Beskrivelse av oppskrift");
CALL sp_InsertRecipeImage(@recipeID,9,1, "./img/saft.png", "Deilig saft bilde");

CALL sp_InsertRecipe("Kake", 1, @recipeID);
CALL sp_InsertRecipeIngredient(@recipeID, 1, 1, "Mel", "300 gram");
CALL sp_InsertRecipeIngredient(@recipeID, 2, 1, "Sukker", "200 gram");
CALL sp_InsertRecipeIngredient(@recipeID, 3, 1, "Kanel", "10 gram");
CALL sp_InsertRecipeIngredient(@recipeID, 4, 1, "Lime Jucie", "2 SS");
CALL sp_InsertRecipeStep(@recipeID,5,1, "Steg 1");
CALL sp_InsertRecipeStep(@recipeID,6,1, "Steg 2");
CALL sp_InsertRecipeStep(@recipeID,7,1, "Steg 3");
CALL sp_InsertRecipeText(@recipeID,8,1, "Beskrivelse av oppskrift");
CALL sp_InsertRecipeImage(@recipeID,9,1, "./img/saft.png", "Deilig saft bilde");

CALL sp_InsertRecipe("Saft", 1, @recipeID);
CALL sp_InsertRecipeIngredient(@recipeID, 1, 1, "Vann", "3 liter");
CALL sp_InsertRecipeIngredient(@recipeID, 2, 1, "Sukker", "200 gram");
CALL sp_InsertRecipeIngredient(@recipeID, 3, 1, "Appelsin Jucie", "5 dl");
CALL sp_InsertRecipeIngredient(@recipeID, 4, 1, "Lime Jucie", "2 SS");
CALL sp_InsertRecipeStep(@recipeID,5,1, "Steg 1");
CALL sp_InsertRecipeStep(@recipeID,6,1, "Steg 2");
CALL sp_InsertRecipeStep(@recipeID,7,1, "Steg 3");
CALL sp_InsertRecipeText(@recipeID,8,1, "Beskrivelse av oppskrift");
CALL sp_InsertRecipeImage(@recipeID,9,1, "./img/saft.png", "Deilig saft bilde");